$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/MotoCalculator)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/SimpleGallery)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/ViMusic)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/ViaBrowser)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/Viper4AndroidFX)
